config/routes.rb
Bloccit::Application.routes.draw do
  
  devise_for :users
  resources :users, only: [:update, :show, :index]
 

 resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index] do 
    resources :comments, only: [:create, :destroy] 
      resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

# Note the only: [] in the top-level post resources line. 
# This is because we don't want to create any /posts/:id routes, 
# just posts/:post_id/comments.
 

get 'about' => 'welcome#about'

  
  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic


  default_scope { order('rank DESC')}
    scope :visible_to, -> (user) {user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  mount_uploader :image, ImageUploader


  def up_votes
    votes.where(value: +1).count
  end

  def down_votes
    votes.where(value: -1).count
  end 

  def points
  #use the fucking methods you defined above
  up_votes - down_votes
  end

  def update_rank
  age = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24)
  new_rank = points + age

  update_attribute(:rank, new_rank)
  end


  def create_vote
    user.votes.create(value: 1, post: self)
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new 
    authorize @topic
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save
      @post.create_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Either it is too short, didn't have a title, or you didn't type anything ya turkey."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.update_attributes (params[:post])
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

    def destroy
        @topic = Topic.find(params[:topic_id])
        @post = @topic.posts.find(params[:post_id])
        @comment = @post.comments.find(params[:id])

        authorize @comment
        if @comment.destroy
          flash[:notice] = "You successfully destroyed this shit."
          redirect_to [@topic, @post]
        else
          flash[:error] = "Nice try but you blew it, try again."
          redirect_to [@topic, @post]
    end
  end
  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
        <div class="media-body">
          <h4 class="media-heading">
            <%= image_tag(post.image.thumb.url) if post.image? %>
            <%= link_to (markdown post.title), [post.topic, post] %>
          </h4>
           <small>
      <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
             submitted <%= time_ago_in_words(post.created_at) %> ago by
             <%= post.user.name %><br/>
             <%= post.comments.count %> Comments

             
   </small>
        </div>
      </div>


 <%= form_for [topic, post] do |f| %>
   <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %> 
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
   <%= render partial: 'votes/voter', locals: { post: post } %>
   <div class="media-body">
     <h4 class="media-heading">
       <%= image_tag(post.image.thumb.url) if post.image? %>
       <%= link_to (markdown post.title), [post.topic, post] %>
     </h4>
     <small>
       <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
       submitted <%= time_ago_in_words(post.created_at) %> ago by
       <%= post.user.name %><br/>
       <%= post.comments.count %> Comments
     </small>
   </div>
 </div>  

app/views/posts/_posts.html.erb
      <div class="media">
         <%= render partial: 'votes/voter', locals: { post: post } %>
         <div class="media-body">
           <h4 class="media-heading">
             <%= image_tag(post.image.thumb.url) if post.image? %>
             <%= link_to (markdown post.title), [post.topic, post] %>
           </h4>
           <small>
             <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
             submitted <%= time_ago_in_words(post.created_at) %> ago by
             <%= post.user.name %><br/>
             <%= post.comments.count %> Comments
           </small>
         </div>
       </div>  

app/views/posts/edit.html.erb
 <h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
<%= render partial: 'form', locals: {topic: @topic, post: @post } %>


   


   </div>
 </div>

app/views/posts/index.html.erb
<h1> All Posts</h1>

<% if policy(Post.new).create? %>
<%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
<% end %>

<% @posts.each do |post| %>
     <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to post.title, post %>
       </h4>
        <small>
         submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
         <%= post.comments.count %> Comments
       </small>
     </div>
   </div>
  <% end %>

   <div class="row">
   <div class="col-md-8">
     <h1>Popular</h1>
     <p class="lead">Active posts this week</p>
     <%= render @posts %>
     <%= will_paginate @posts %>
   </div>
   <div class="col-md-4">
   </div>
 </div>

app/views/posts/show.html.erb
 

<div class="row">
  <div class="span8">
      <%= render partial: 'votes/voter', locals: { post: @post } %>
      <h1><%= markdown @post.title %></h1>
    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by 
      <%= @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
    <p><%= image_tag(@post.image_url) if @post.image? %></p>
    
    <hr/>

    <h2> Comments</h2>
    
    <% @post.comments.each do |comment| %> 
    <%= render comment %>
    <% end%>
    
    <% if policy(Comment.new).create? %>
      <hr/>
      <h4>New Comment</h4>
      <%= render partial: 'comments/form', locals: { topic: @topic, post: @post, comment: @comment } %>
    <% end %>

      <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic,@post), class: 'btn btn-success' %>
    <% end %>
     <% if policy(@post).destroy? %>
       <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
     <% end %>

        <div>
          <h3><%= pluralize(@post.points, 'point') %></h3>
          <small>
            <%= pluralize(@post.up_votes, 'up vote') %>, 
            <%= pluralize(@post.down_votes, 'down vote') %>
          </small>
        </div>
        <%= render partial: 'favorites/favorite', locals: { post: @post } %>
  </div>
  
  </div>
  
  
  

</div>